"""Initial migration

Revision ID: 52200cc2924e
Revises: 
Create Date: 2025-12-23 13:29:22.432397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52200cc2924e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CRAWLING', 'PARSING', 'SAVING', 'DONE', 'ERROR', name='ingestionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_url'), 'ingestion_jobs', ['source_url'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'UNKNOWN', name='novelstatus'), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_index(op.f('ix_novels_slug'), 'novels', ['slug'], unique=True)
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_one_shot', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_is_one_shot'), 'chapters', ['is_one_shot'], unique=False)
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_index(op.f('ix_chapters_slug'), 'chapters', ['slug'], unique=False)
    op.create_index(op.f('ix_chapters_title'), 'chapters', ['title'], unique=False)
    op.create_table('novel_genres',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('novel_id', 'genre_id')
    )
    op.create_index('ix_novel_genres_genre_id', 'novel_genres', ['genre_id'], unique=False)
    op.create_index('ix_novel_genres_novel_id', 'novel_genres', ['novel_id'], unique=False)
    op.create_table('chapter_genres',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id', 'genre_id')
    )
    op.create_index('ix_chapter_genres_chapter_id', 'chapter_genres', ['chapter_id'], unique=False)
    op.create_index('ix_chapter_genres_genre_id', 'chapter_genres', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_genres_genre_id', table_name='chapter_genres')
    op.drop_index('ix_chapter_genres_chapter_id', table_name='chapter_genres')
    op.drop_table('chapter_genres')
    op.drop_index('ix_novel_genres_novel_id', table_name='novel_genres')
    op.drop_index('ix_novel_genres_genre_id', table_name='novel_genres')
    op.drop_table('novel_genres')
    op.drop_index(op.f('ix_chapters_title'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_slug'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_is_one_shot'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_index(op.f('ix_novels_slug'), table_name='novels')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_url'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
